dwm-financas/Models/Repositories/BalanceteMensalViewModel.cs
namespace DWM.Models.Repositories
{
    public class BalanceteMensalViewModel : PlanoContaViewModel
    {
        public System.Nullable<int> sequencial { get; set; }
        public System.Nullable<decimal> vr_saldo_ant { get; set; }
        public System.Nullable<decimal> vr_debito_1 { get; set; }
        public System.Nullable<decimal> vr_credito_1 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_1 { get; set; }
        public System.Nullable<decimal> vr_debito_2 { get; set; }
        public System.Nullable<decimal> vr_credito_2 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_2 { get; set; }
        public System.Nullable<decimal> vr_debito_3 { get; set; }
        public System.Nullable<decimal> vr_credito_3 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_3 { get; set; }
        public System.Nullable<decimal> vr_debito_4 { get; set; }
        public System.Nullable<decimal> vr_credito_4 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_4 { get; set; }
        public System.Nullable<decimal> vr_debito_5 { get; set; }
        public System.Nullable<decimal> vr_credito_5 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_5 { get; set; }
        public System.Nullable<decimal> vr_debito_6 { get; set; }
        public System.Nullable<decimal> vr_credito_6 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_6 { get; set; }
        public System.Nullable<decimal> vr_debito_7 { get; set; }
        public System.Nullable<decimal> vr_credito_7 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_7 { get; set; }
        public System.Nullable<decimal> vr_debito_8 { get; set; }
        public System.Nullable<decimal> vr_credito_8 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_8 { get; set; }
        public System.Nullable<decimal> vr_debito_9 { get; set; }
        public System.Nullable<decimal> vr_credito_9 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_9 { get; set; }
        public System.Nullable<decimal> vr_debito_10 { get; set; }
        public System.Nullable<decimal> vr_credito_10 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_10 { get; set; }
        public System.Nullable<decimal> vr_debito_11 { get; set; }
        public System.Nullable<decimal> vr_credito_11 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_11 { get; set; }
        public System.Nullable<decimal> vr_debito_12 { get; set; }
        public System.Nullable<decimal> vr_credito_12 { get; set; }
        public System.Nullable<decimal> vr_saldo_atual_12 { get; set; }
    }
}

dwm-financas/Controllers/BalanceteMensalController.cs
using App_Dominio.Controllers;
using DWM.Models.Repositories;
using System;
using System.Web.Mvc;
using App_Dominio.Security;
using App_Dominio.Pattern;
using DWM.Models.Entidades;
using DWM.Models.BI;
using System.Collections.Generic;
using App_Dominio.Repositories;
using App_Dominio.Entidades;

namespace DWM.Controllers
{
    public class BalanceteMensalController : ReportController<BalanceteMensalViewModel>
    {
        #region Herança
        public override int _sistema_id() { return (int)DWM.Models.Enumeracoes.Sistema.DWMFINANCAS; }

        public override bool mustListOnLoad()
        {
            if (Request["TipoBalanceteMensal"] != null && Request["TipoBalanceteMensal"] != "")
                return true;
            else
                return false;
        }

        public override string getListName()
        {
            return "Balancete Mensal";
        }

        //public override bool ClearBreadCrumbOnBrowse()
        //{
        //    return Request["id"] == null;
        //}
        #endregion    

        #region List
        public override ActionResult List(int? index, int? PageSize, string descricao = null)
        {
            if (Request["TipoBalanceteMensal"] != null && Request["TipoBalanceteMensal"] != "")
                return ListParam(0, 1000, Request["TipoBalanceteMensal"], 
                                Request["centroCustoId"] != null && Request["centroCustoId"] != "" ? int.Parse(Request["centroCustoid"]) : 0,
                                Request["grauPC"] != null && Request["grauPC"] != "" ? int.Parse(Request["grauPC"]) : 0,
                                Request["descricao_centroCusto"], Request["RecDesp"]);
            else
                return ListParam(0, 1000);
        }

        [AuthorizeFilter]
        public ActionResult ListParam(int? index, int? pageSize = 100, string TipoBalanceteMensal = "T", 
                                        int centroCustoId = 0, int grauPC = 0, string descricao_centroCusto = "", string RecDesp = "N")
        {
            if (ViewBag.ValidateRequest)
            {
                Factory<ExercicioViewModel, ApplicationContext> facade = new Factory<ExercicioViewModel, ApplicationContext>();
                ExercicioViewModel e = facade.Execute(new ExercicioBI(), new ExercicioViewModel());

                ListViewBalanceteMensalBI bal = new ListViewBalanceteMensalBI();
                return this._List(index,
                                    pageSize,
                                    "Browse",
                                    bal,
                                    TipoBalanceteMensal,
                                    centroCustoId,
                                    e.exercicio,
                                    grauPC,
                                    descricao_centroCusto,
                                    RecDesp);
            }
            else
                return View();
        }

        public ActionResult _List(int? index, int? pageSize, string action, ListViewBalanceteMensalBI model, params object[] param)
        {
            if (ViewBag.ValidateRequest)
            {
                Factory<BalanceteMensalViewModel, ApplicationContext> facade = new Factory<BalanceteMensalViewModel, ApplicationContext>();
                IPagedList pagedList = facade.PagedList(model, index, pageSize.Value, param);
                UpdateBreadCrumb(this.ControllerContext.RouteData.Values["controller"].ToString(), action);

                #region Filtros
                pagedList.Filtros = new List<FiltroRepository>();

                #region Tipo de Balancete (S-Saldos ou T-Totais de Débito e Crédito)
                FiltroRepository TipoBalanceteMensalFiltro = new FiltroRepository()
                {
                    atributo = "TipoBalanceteMensal",
                    valor = param[0].ToString()
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(TipoBalanceteMensalFiltro);
                #endregion

                #region Centro de Custo
                FiltroRepository CentroCustoFiltro = new FiltroRepository()
                {
                    atributo = "centroCustoId",
                    valor = param[1].ToString()
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(CentroCustoFiltro);
                #endregion

                #region Exercicio
                FiltroRepository ExercicioFiltro = new FiltroRepository()
                {
                    atributo = "centroCustoId",
                    valor = param[2].ToString()
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(ExercicioFiltro);
                #endregion

                #region GrauPC
                FiltroRepository GrauPCFiltro = new FiltroRepository()
                {
                    atributo = "centroCustoId",
                    valor = param[3].ToString()
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(GrauPCFiltro);
                #endregion

                #region Empresa
                EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
                FiltroRepository EmpresaFiltro = new FiltroRepository()
                {
                    atributo = "empresa",
                    valor = security.getEmpresa().nome
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(EmpresaFiltro);
                #endregion

                #region Descrição Centro de Custo
                string descricao_centroCusto = (string)param[4];

                FiltroRepository DescricaoCentroCustoFiltro = new FiltroRepository()
                {
                    atributo = "DescricaoCentroCustoFiltro",
                    valor = String.IsNullOrEmpty(descricao_centroCusto) ? "<< Todos os centros de custos >>" : descricao_centroCusto
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(DescricaoCentroCustoFiltro);
                #endregion

                #region Receitas e Despesas
                FiltroRepository RecDespFiltro = new FiltroRepository()
                {
                    atributo = "RecDesp",
                    valor = (string)param[5]
                };
                ((IList<FiltroRepository>)pagedList.Filtros).Add(RecDespFiltro);
                #endregion
                #endregion

                return View(pagedList);
            }
            else
                return null;
        }
        #endregion

        #region Imprimir
        [AuthorizeFilter]
        public ActionResult Imprimir(string TipoBalanceteMensal = "", int centroCustoId = 0, int grauPC = 0, string descricao_centroCusto = "", string RecDesp = "N")
        {
            return ListParam(0, 10000, TipoBalanceteMensal, centroCustoId, grauPC, descricao_centroCusto, RecDesp);
        }
        #endregion

    }
}

dwm-financas/Views/BalanceteMensal/Browse.cshtml
@using DWM.Models.Repositories
@using App_Dominio.Repositories
@using DWM.Models.Enumeracoes
@model PagedList<BalanceteMensalViewModel>
@{
    TransacaoRepository[] t = { new TransacaoRepository(), new TransacaoRepository() };
    t[0].url = "../Contabilidade/Create";
    t[0].nomeCurto = "Incluir";
    t[0].exibir = "S";
    t[0].referencia = "";

    t[1].url = "../Home/Default";

    string value = "";
    string Text = "";

    if (Request["centroCustoId"] != null && Request["centroCustoId"] != "")
    {
        value = Request["centroCustoId"];
        Text = Request["descricao_centroCusto"];
    }
}
<!-- Datatables -->
<link href="../Content/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">

@Html.Partial("_alerts")
@Html.Partial("_AjaxAlert", "")
<div class="x_panel">
    @Html.EditorFor(info => Model, "FORMULARIO", new { Brand = "Balancete Mensal", Descricao = "", Transacao = t })
    <div class="x_content">
        @using (Ajax.BeginForm("ListParam", "BalanceteMensal", new AjaxOptions { HttpMethod = "get", UpdateTargetId = "div-list-static" }, new { @role = "search", @id = "form0", @name = "form0" }))
            {
            @Html.Hidden("planoContaId")
            @Html.Hidden("descricao_conta")
            @Html.Hidden("codigoPleno")
            @Html.Hidden("totalizaConta", "S")
            @Html.Hidden("totalizaDia", "N")
            @Html.Hidden("grauPC", "0")
            @Html.Hidden("RecDesp", "N")
            @Html.Hidden("Data1")
            @Html.Hidden("Data2")
            <div class="row clearfix">
                <div class="col-md-4">
                    @Html.Editor("descricao_centroCusto1", "CentroCustoAutoComplete", new { nextField = "data1", prevField = "descricao_conta", value = value, Text = Text })
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label" for="data1">Tipo</label>
                        @if (Model != null && Model.Filtros != null && Model.Filtros.Count() > 0)
                        {
                            @Html.DropDownList("TipoBalanceteMensal", new BindDropDownList().TipoBalanceteMensal(Model.Filtros.ElementAt(0).valor), new { @class = "form-control" })
                        }
                        else
                        {
                            @Html.DropDownList("TipoBalanceteMensal", new BindDropDownList().TipoBalanceteMensal("T"), new { @class = "form-control" })
                        }
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="form-group">
                        <a href="#panel-detail" class="btn btn-primary" onclick="validaBal(0);">Buscar</a>
                        <input type="button" class="btn btn-default" onclick="window.location = '../Contabilidade/Create'" value="Incluir" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div id="div-list-static">
    @if (Model != null)
    {
        @Html.Partial("ListParam", Model)
    }
</div>


<script>
    $(function () {
        $('#form0').submit(function () {
            if ($(this).valid()) {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        $('#div-list-static').html(result);
                    }
                });
            }
            return false;
        });
    });

    function validaBal(grauPC) {
        $('#grauPC').val(grauPC);
        $('#RecDesp').val("N");
        Refresh(0, getPageSize(), 'ListParam', 'div-list-static');
        $('#div-list-static').html('');
    }

    function BalanceteRecDesp(grauPC) {
        $('#RecDesp').val("S");
        $('#grauPC').val(grauPC);
        Refresh(0, getPageSize(), 'ListParam', 'div-list-static');
        $('#div-list-static').html('');
    }

    //function validaPDF()
    //{
    //    if ($('#planoContaId').val() == null || $('#planoContaId').val() == '') {
    //        ShowMessageAlert('É preciso informar a conta para a emissão do Razão', 'warning');
    //        return false;
    //    }
    //    else
    //        return true;
    //}

</script>

dwm-financas/Views/BalanceteMensal/Imprimir.cshtml
@using DWM.Models.Repositories
@using App_Dominio.Repositories
@using DWM.Models.Repositories;

@model PagedList<BalanceteMensalViewModel>
@{
    Layout = null;
    string font = "normal";

    string _TipoBalanceteMensal = Model.Filtros.ElementAt(0).valor;
    string _exercicio = Model.Filtros.ElementAt(2).valor;
    string _data1 = "01/01/" + _exercicio;
    string _data2 = "31/12/" + _exercicio;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Balancete</title>
    @Styles.Render("~/Content-z/css")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body style="background-color: #fff">
    <h2 style="text-align: center">Balancete Mensal</h2>
    <h2 style="text-align: center">Empresa: @Model.Filtros.ElementAt(4).valor</h2>
    <h2 style="text-align: center">Exercício: @Model.Filtros.ElementAt(2).valor</h2>
    <h2 style="text-align: center">Centro de custo: @Model.Filtros.ElementAt(5).valor</h2>
    <hr />
    <table class="table" style="orphans: 3;">
        <thead>
            <tr class="headings">
                <th style="font-family: Tahoma; font-size: 9px; text-align: left" class="column-title text-center">Código Pleno</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: left" class="column-title">Descrição</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Saldo Anterior</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Jan</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Fev</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Mar</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Abr</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Mai</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Jun</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Jul</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Ago</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Set</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Out</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Nov</th>
                <th style="font-family: Tahoma; font-size: 9px; text-align: right">Dez</th>
                @if (_TipoBalanceteMensal == "T")
                {
                    <th style="text-align: right">Saldo Atual</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (BalanceteMensalViewModel balancete in Model)
            {
                if (balancete.planoContaId_pai.HasValue)
                {
                    font = "normal";
                }
                else
                {
                    font = "bold";
                }
                <tr class="even pointer" style="font-weight: @font">
                    <td class="text-center">
                        <span style="font-family: Tahoma; font-size: 9px">@balancete.codigoPleno</span>
                    </td>
                    <td>
                        <span style="font-family: Tahoma; font-size: 9px">@balancete.descricao</span>
                    </td>
                    <td class="text-right">
                        <span style="font-family: Tahoma; font-size: 9px">@balancete.vr_saldo_ant.Value.ToString("###,###,##0.00")</span>
                    </td>
                    @if (_TipoBalanceteMensal == "T")
                    {
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_1.Value - balancete.vr_credito_1.Value != 0 ? (balancete.vr_debito_1.Value - balancete.vr_credito_1.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_2.Value - balancete.vr_credito_2.Value != 0 ? (balancete.vr_debito_2.Value - balancete.vr_credito_2.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_3.Value - balancete.vr_credito_3.Value != 0 ? (balancete.vr_debito_3.Value - balancete.vr_credito_3.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_4.Value - balancete.vr_credito_4.Value != 0 ? (balancete.vr_debito_4.Value - balancete.vr_credito_4.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_5.Value - balancete.vr_credito_5.Value != 0 ? (balancete.vr_debito_5.Value - balancete.vr_credito_5.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_6.Value - balancete.vr_credito_6.Value != 0 ? (balancete.vr_debito_6.Value - balancete.vr_credito_6.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_7.Value - balancete.vr_credito_7.Value != 0 ? (balancete.vr_debito_7.Value - balancete.vr_credito_7.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_8.Value - balancete.vr_credito_8.Value != 0 ? (balancete.vr_debito_8.Value - balancete.vr_credito_8.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_9.Value - balancete.vr_credito_9.Value != 0 ? (balancete.vr_debito_9.Value - balancete.vr_credito_9.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_10.Value - balancete.vr_credito_10.Value != 0 ? (balancete.vr_debito_10.Value - balancete.vr_credito_10.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_11.Value - balancete.vr_credito_11.Value != 0 ? (balancete.vr_debito_11.Value - balancete.vr_credito_11.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_debito_12.Value - balancete.vr_credito_12.Value != 0 ? (balancete.vr_debito_12.Value - balancete.vr_credito_12.Value).ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@balancete.vr_saldo_atual_12.Value.ToString("###,###,##0.00")</span>
                        </td>
                    }
                    else
                    {
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_1.Value != 0 ? @balancete.vr_saldo_atual_1.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_2.Value != 0 ? @balancete.vr_saldo_atual_2.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_3.Value != 0 ? @balancete.vr_saldo_atual_3.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_4.Value != 0 ? @balancete.vr_saldo_atual_4.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_5.Value != 0 ? @balancete.vr_saldo_atual_5.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_6.Value != 0 ? @balancete.vr_saldo_atual_6.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_7.Value != 0 ? @balancete.vr_saldo_atual_7.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_8.Value != 0 ? @balancete.vr_saldo_atual_8.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_9.Value != 0 ? @balancete.vr_saldo_atual_9.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_10.Value != 0 ? @balancete.vr_saldo_atual_10.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_11.Value != 0 ? @balancete.vr_saldo_atual_11.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                        <td class="text-right">
                            <span style="font-family: Tahoma; font-size: 9px">@(balancete.vr_saldo_atual_12.Value != 0 ? @balancete.vr_saldo_atual_12.Value.ToString("###,###,##0.00") : "")</span>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</body>
</html>