dwm-financas/Controllers/ExtratoController.cs
using App_Dominio.Controllers;
using DWM.Models.Repositories;
using System;
using System.Web.Mvc;
//using Microsoft.Reporting.WebForms;
using DWM.Models.Enumeracoes;
using DWM.Models.Report;
using App_Dominio.Security;
using App_Dominio.Pattern;
using DWM.Models.Entidades;
using DWM.Models.BI;

namespace DWM.Controllers
{
    public class ExtratoController : ReportController<ExtratoViewModel>
    {
        #region Herança
        public override int _sistema_id() { return (int)Sistema.DWMFINANCAS; }

        public override bool mustListOnLoad()
        {
            Factory<ExercicioViewModel, ApplicationContext> facade = new Factory<ExercicioViewModel, ApplicationContext>();
            ExercicioViewModel e = facade.Execute(new ExercicioBI(), new ExercicioViewModel());

            if (e.mensagem.Code == 0 && e.dt_lancamento_inicio.HasValue)
            {
                ViewData["dt_lancamento_inicio"] = e.dt_lancamento_inicio.Value;
                ViewData["dt_lancamento_fim"] = e.dt_lancamento_fim.Value;
            }
            else
            {
                ViewData["dt_lancamento_inicio"] = Convert.ToDateTime(DateTime.Today.ToString("yyyy-MM-") + "01");
                ViewData["dt_lancamento_fim"] = Convert.ToDateTime(DateTime.Today.AddMonths(1).ToString("yyyy-MM-") + "01").AddDays(-1);
            }

            if (Request["bancoId"] != null)
                return true;
            else
                return false;
        }

        public override string getListName()
        {
            return "Extrato Bancário";
        }
        #endregion    

        #region List
        public override ActionResult List(int? index, int? PageSize, string descricao = null)
        {
            if (Request ["bancoId"] == null)
                return ListParam(index, PageSize);
            else
                return ListParam(index, PageSize, Request["data1"], Request["data2"], int.Parse(Request["bancoId"]), Request["nome_banco"]);
        }

        [AuthorizeFilter]
        public ActionResult ListParam(int? index, int? pageSize = 50, string data1 = "", string data2 = "",
                                        int? bancoId = null, string nome_banco = "")
        {
            if (ViewBag.ValidateRequest)
            {
                if (!bancoId.HasValue)
                {
                    Attention("É preciso informar o banco para a emissão do Extrato");
                    return View();
                }

                if (data1 == "" || data1.Contains("%"))
                {
                    Factory<ExercicioViewModel, ApplicationContext> facade = new Factory<ExercicioViewModel, ApplicationContext>();
                    ExercicioViewModel e = facade.Execute(new ExercicioBI(), new ExercicioViewModel());

                    if (e.mensagem.Code == 0 && e.dt_lancamento_inicio.HasValue)
                    {
                        data1 = e.dt_lancamento_inicio.Value.ToString("yyyy-MM-dd");
                        data2 = e.dt_lancamento_fim.Value.ToString("yyyy-MM-dd");
                    }
                    else
                    {
                        data1 = DateTime.Today.ToString("yyyy-MM-") + "01";
                        data2 = Convert.ToDateTime(DateTime.Today.AddMonths(1).ToString("yyyy-MM-") + "01").AddDays(-1).ToString("yyyy-MM-dd");
                    }

                    //data1 = DateTime.Today.ToString("yyyy-MM-") + "01";
                    //data2 = Convert.ToDateTime(DateTime.Today.AddMonths(1).ToString("yyyy-MM-") + "01").AddDays(-1).ToString("yyyy-MM-dd");
                }

                ExtratoReport ext = new ExtratoReport();
                return this._List(index, pageSize, "Browse", ext, data1, data2, bancoId);
            }
            else
                return View();
        }
        #endregion

        #region Imprimir
        [AuthorizeFilter]
        public ActionResult Imprimir(string data1 = "", string data2 = "",
                                        int? bancoId = null, string nome_banco = "")
        {
            return ListParam(0, 10000, data1, data2, bancoId, nome_banco);
        }
        #endregion


    }
}

dwm-financas/Views/Extrato/Browse.cshtml
@using DWM.Models.Repositories
@using App_Dominio.Repositories
@model PagedList<ExtratoViewModel>
@{
    TransacaoRepository[] t = { new TransacaoRepository(), new TransacaoRepository(), new TransacaoRepository(), new TransacaoRepository(), new TransacaoRepository() };
    t[0].url = "../MovimentoBancario/Create";
    t[0].nomeCurto = "Movimento bancário";
    t[0].exibir = "S";
    t[0].referencia = "";
    t[0].glyph = "fa fa-file-o";


    t[1].url = "../Cobranca/Create";
    t[1].nomeCurto = "Cobrança";
    t[1].exibir = "S";
    t[1].referencia = "";
    t[1].glyph = "fa fa-barcode";

    t[2].url = "../ContaPagar/Create";
    t[2].nomeCurto = "Contas a pagar";
    t[2].exibir = "S";
    t[2].referencia = "";
    t[2].glyph = "fa fa-dollar";

    t[3].url = "#";
    t[3].nomeCurto = "Imprimir";
    t[3].exibir = "S";
    t[3].referencia = "Print()";

    t[4].url = "../Home/Default";

    string BancoValue = "";
    string BancoText = "";

    if (Request["bancoId"] != null && Request["bancoId"] != "")
    {
        BancoValue = Request["bancoId"];
        BancoText = Request["nome_banco"];
    }

}
<!-- Datatables -->
<link href="../Content/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">

<div class="container-cadastro">
    @Html.Partial("_AjaxAlert", "")
    @Html.Partial("_alerts")
    <div class="x_panel" id="panel-top">
        @Html.EditorFor(info => Model, "FORMULARIO", new { Brand = "Extrato bancário", Descricao = "", Transacao = t })
        <div class="x_content">
            @Html.Partial("_AjaxAlert", "panel-top")
            @using (Ajax.BeginForm("ListParam", "Extrato", new AjaxOptions { HttpMethod = "get", UpdateTargetId = "div-list-extrato" }, new { @role = "search", @id = "form0" }))
            {
                DateTime? d1 = Request["data1"] == null || Request["data1"].Contains("%") ? (DateTime)ViewData["dt_lancamento_inicio"] : Convert.ToDateTime(Request["data1"]);
                DateTime? d2 = Request["data2"] == null || Request["data2"].Contains("%") ? (DateTime)ViewData["dt_lancamento_fim"] : Convert.ToDateTime(Request["data2"]);

                <div class="row clearfix">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                        @Html.Editor("nome_banco1", "BancosAutoComplete", new { nextField = "data1", value = BancoValue, Text = BancoText })
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="dt_emissao1">Período</label>
                            <div class="row clearfix">
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-5">
                                    <input type="date" class="form-control" name="data1" id="data1" value="@d1.Value.ToString("yyyy-MM-dd")" />
                                </div>
                                <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                                    à
                                </div>
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-5">
                                    <input type="date" class="form-control" name="data2" id="data2" value="@d2.Value.ToString("yyyy-MM-dd")" />
                                </div>
                                <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-md-12">
                        <div class="form-group">
                            @*<input type="submit" class="btn btn-primary" value="Buscar" id="btn-buscar" name="btn-buscar" onclick="return validaExtrato();" />*@
                            <a href="#panel-detail" class="btn btn-primary" onclick="validaExtrato();">Buscar</a>
                            <input type="button" class="btn btn-default" onclick="window.location = '../MovimentoBancario/Create'" value="Incluir" />
                        </div>
                    </div>
                </div>
            }
            <div id="div-list-extrato">
                @if (Model != null)
                {
                    @Html.Partial("ListParam", Model)
                }
            </div>
        </div>
    </div>
</div>

<script>
    //$(function () {
    //    $('#form000').submit(function () {
    //        if ($(this).valid()) {
    //            $.ajax({
    //                url: this.action,
    //                type: this.method,
    //                data: $(this).serialize(),
    //                success: function (result) {
    //                    $('#div-list-extrato').html(result);
    //                }
    //            });
    //        }
    //        return false;
    //    });
    //});

    function validaExtrato() {
        if ($('#bancoId').val() == null || $('#bancoId').val() == '') {
            ShowMessageAjaxAlert('É preciso informar o banco para a emissão do Extrato', 'warning');
        }
        else {
            Refresh(0, getPageSize(), 'ListParam', 'div-list-extrato');
            $('#div-list-extrato').html('');
        }
    }

    function Print() {
        if ($('#bancoId').val() == null || $('#bancoId').val() == '') {
            ShowMessageAjaxAlert('É preciso informar o banco para a emissão do Extrato', 'warning');
            return;
        }

        var link = "../Extrato/Imprimir?data1=" + $('#data1').val() +
                   "&data2=" + $('#data2').val() +
                   "&bancoId=" + $('#bancoId').val() +
                   "&nome_banco=" + $('#nome_banco').val() +
                   "&hoje=" + new Date();

        window.open(link);
    }

    //function validaPDF()
    //{
    //    if ($('#bancoId').val() == null || $('#bancoId').val() == '') {
    //        ShowMessageAjaxAlert('É preciso informar o banco para a emissão do Extrato', 'warning');
    //        return false;
    //    }
    //    else
    //        return true;
    //}

</script>

dwm-financas/Views/Extrato/Imprimir.cshtml
@using App_Dominio.Entidades;
@using App_Dominio.Security;
@using DWM.Models.Repositories
@using DWM.Models.Repositories;
@model PagedList<DWM.Models.Repositories.ExtratoViewModel>
@{
    Layout = null;
    string vr_db = "";
    string vr_cr = "";
    string vr_sld = "";
    string color = "#000";
    EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Extrato Bancário</title>
    @Styles.Render("~/Content-z/css")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body style="background-color: #fff">
    <h2 style="text-align: center">Extrato Bancário</h2>
    <h2 style="text-align: center">Empresa: @security.getEmpresa().nome</h2>
    <h2 style="text-align: center">Período: @(Request["data1"]) à @(Request["data2"])</h2>
    <h2 style="text-align: center">Banco: @(Request["nome_banco"])</h2>
    <hr />
    <table class="table" style="orphans: 3;">
        <thead>
            <tr class="headings">
                <th>Data</th>
                <th>Doc</th>
                <th>Histórico</th>
                <th class="text-right">Débito</th>
                <th class="text-right">Crédito</th>
                <th class="text-right">Saldo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ExtratoViewModel extrato in Model.Where(info => info.descricao_historico != null))
            {
                string cor_db = "";
                string cor_cr = "";
                string cor_sld = "";
                vr_db = "";
                vr_cr = "";
                if (extrato.vr_debito.HasValue && extrato.vr_debito > 0)
                {
                    vr_db = extrato.vr_debito.HasValue ? extrato.vr_debito.Value.ToString("###,###,###,##0.00") : "";
                    cor_db = "text-bold";
                }
                if (extrato.vr_credito.HasValue && extrato.vr_credito > 0)
                {
                    vr_cr = extrato.vr_credito.HasValue ? extrato.vr_credito.Value.ToString("###,###,###,##0.00") : "";
                    cor_cr = "text-bold";
                }
                if (extrato.vr_saldo != null)
                {
                    vr_sld = extrato.vr_saldo != null ? extrato.vr_saldo.Value.ToString("###,###,###,##0.00") : "";
                    cor_sld = "text-bold";
                }
                if (extrato._dt_movto != null && extrato._dt_movto > DateTime.Today)
                {
                    if (color != "#A4A4A4")
                    {
                        <tr style="background-color: #D8D8D8">
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="text-center text-mama-africa"><h4><strong>Operações Agendadas</strong></h4></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    }
                    color = "#A4A4A4";
                }
                else if (extrato._dt_movto > Convert.ToDateTime("1980-01-01"))
                {
                    color = "";
                }
                <tr>
                    <td style="color: @color">
                        @if (extrato._dt_movto > Convert.ToDateTime("1980-01-01"))
                        {
                            <span>@extrato.dt_movto.ToString("dd/MM/yyyy")</span>
                        }
                    </td>
                    <td style="color: @color">
                        <span>@extrato.documento</span>
                    </td>
                    <td style="color: @color">
                        @if (extrato.descricao_historico != null && extrato.descricao_historico.Contains("<b>"))
                        {
                            <span><strong>@extrato.descricao_historico.Replace("<b>", "").Replace("</b>", "")</strong></span>
                        }
                        else
                        {
                            <span>@extrato.descricao_historico</span>
                        }
                        @if (extrato.complementoHist != null && extrato.complementoHist.Trim() != "")
                        {
                            <small>@Html.DisplayTextFor(info => extrato.complementoHist)</small>
                        }
                    </td>
                    <td style="color: @color" class="text-right @cor_db">
                        <span>@vr_db</span>
                    </td>
                    <td style="color: @color" class="text-right @cor_cr">
                        <span>@vr_cr</span>
                    </td>
                    <td style="color: @color" class="text-right @cor_sld">
                        <span>@Html.DisplayTextFor(info => vr_sld)</span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

dwm-financas/Views/Extrato/ListParam.cshtml
@model PagedList<DWM.Models.Repositories.ExtratoViewModel>
@using DWM.Models.Repositories;
@{
    Layout = null;
    string vr_db = "";
    string vr_cr = "";
    string vr_sld = "";
    string color = "#000";
    string operacao = Request["id"] != null && Request["id"] == "E" ? "Delete" : "Edit";
}
@if (Model != null)
{
    <div class="dashboard-widget-content" id="panel-detail">
        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action" id="datatable">
                <thead>
                    <tr class="heading">
                        <th>Data</th>
                        <th>Doc</th>
                        <th>Histórico</th>
                        <th class="text-right">Débito</th>
                        <th class="text-right">Crédito</th>
                        <th class="text-right">Saldo</th>
                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ExtratoViewModel extrato in Model.Where(info => info.descricao_historico != null))
                    {
                        string cor_db = "";
                        string cor_cr = "";
                        string cor_sld = "";
                        vr_db = "";
                        vr_cr = "";
                        if (extrato.vr_debito.HasValue && extrato.vr_debito > 0)
                        {
                            vr_db = extrato.vr_debito.HasValue ? extrato.vr_debito.Value.ToString("###,###,###,##0.00") : "";
                            cor_db = "";
                        }
                        if (extrato.vr_credito.HasValue && extrato.vr_credito > 0)
                        {
                            vr_cr = extrato.vr_credito.HasValue ? extrato.vr_credito.Value.ToString("###,###,###,##0.00") : "";
                            cor_cr = "";
                        }
                        if (extrato.vr_saldo != null)
                        {
                            vr_sld = extrato.vr_saldo != null ? extrato.vr_saldo.Value.ToString("###,###,###,##0.00") : "";
                            cor_sld = "";
                        }
                        if (extrato._dt_movto != null && extrato._dt_movto > DateTime.Today)
                        {
                            if (color != "#695A5A")
                            {
                                <tr style="background-color: #D8D8D8">
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td class="text-center text-mama-africa"><h4><strong>Operações Agendadas</strong></h4></td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                </tr>
                            }
                            color = "#695A5A";
                        }
                        else if (extrato._dt_movto > Convert.ToDateTime("1980-01-01"))
                        {
                            color = "#000000";
                        }
                        <tr>
                            <td style="color: @color">
                                @if (extrato._dt_movto > Convert.ToDateTime("1980-01-01"))
                                {
                                    <span>@extrato.dt_movto.ToString("dd/MM/yyyy")</span>
                                }
                            </td>
                            <td style="color: @color">
                                <span>@extrato.documento</span>
                            </td>
                            <td style="color: @color">
                                @if (extrato.descricao_historico != null && extrato.descricao_historico.Contains("<b>"))
                                {
                                    <span><strong>@extrato.descricao_historico.Replace("<b>", "").Replace("</b>", "")</strong></span>
                                }
                                else
                                {
                                    <span>@extrato.descricao_historico</span>
                                }
                                @if (extrato.complementoHist != null && extrato.complementoHist.Trim() != "")
                                {
                                    <small>@Html.DisplayTextFor(info => extrato.complementoHist)</small>
                                }
                            </td>
                            <td style="color: @color" class="text-right @cor_db">
                                <span>@vr_db</span>
                            </td>
                            <td style="color: @color" class="text-right @cor_cr">
                                <span>@vr_cr</span>
                            </td>
                            <td style="color: @color" class="text-right @cor_sld">
                                <span>@Html.DisplayTextFor(info => vr_sld)</span>
                            </td>
                            <td style="color: @color" class="text-center">
                                @if (extrato.operacaoId > 0 && extrato.vr_credito.HasValue && extrato.vr_credito > 0)
                                {
                                    <button type="button" class="btn btn-primary btn-sm glyphicon glyphicon-edit" title="Editar" onclick="window.location='../Cobranca/Edit?OperacaoId=@extrato.operacaoId.ToString()&parcelaId=@extrato.parcelaId.ToString()'"></button>
                                }
                                else if (extrato.operacaoId > 0 && extrato.vr_debito.HasValue && extrato.vr_debito > 0)
                                {
                                    <button type="button" class="btn btn-primary btn-sm glyphicon glyphicon-edit" title="Editar" onclick="window.location='../ContaPagar/Edit?OperacaoId=@extrato.operacaoId.ToString()&parcelaId=@extrato.parcelaId.ToString()'"></button>
                                }
                                else
                                {
                                    <a href="#panel-top" class="btn btn-default btn-sm glyphicon glyphicon-edit" title="Não é possível editar" onclick="ShowMessageAjaxAlert('Este registro não pode ser editado.', 'warning');"></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a href="#panel-detail" class="info pull-right" id="linkTopo"><i class="fa fa-toggle-up"></i> Topo</a>
        </div>
    </div>
    <script>
        document.getElementById("linkTopo").click();
    </script>
}
else if (TempData[App_Dominio.Controllers.Alerts.ATTENTION] != null)
{
    @Html.Partial("_alerts")
}
else
{
    @Html.Partial("_AcessoNegadoModal")
}


<!-- Datatables -->
<script src="../Content/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="../Content/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<script>
    $('#datatable').DataTable({
        lengthMenu: [[15, 25, 50, 100, -1], [15, 25, 50, 100, "Todos"]],
        iDisplayLength: 100,
        language: {
            "url": "../Scripts/DataTablePtBr.txt"
        },
        "bSort": false,
    });
</script>